import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { useContext, useCallback, useEffect } from "react"
import React, { useState } from 'react';

import { getDollaDollaBillsYall } from "services/dolar-blues"

const Home: NextPage = () => {

  const [precio, setPrecio] = useState('');

  useEffect(() => {
    // declare the data fetching function
    const fetchData = async () => {
      const dollaDollaBillsYall = await getDollaDollaBillsYall();
      const dolarBluePrecioCompra = dollaDollaBillsYall[1].casa.compra;
      setPrecio(dolarBluePrecioCompra);
    }
  
    // call the function
    fetchData()
      // make sure to catch any error
      .catch(console.error);
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* make btc and usd tracker... dolar blue. y relacionados.
        https://www.dolarsi.com/api/api.php?type=valoresprincipales using axios */}

       
        <h1 className={styles.title}>
          

          According to Dolarsi.com  -&gt; Dolar Blue Today is: 
           {precio}
     
        </h1>
       
      </main>

      <footer className={styles.footer}>
     
      </footer>
    </div>
  )
}

export default Home
